version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm i @cloudflare/wrangler -g
      - run: wrangler publish
workflows:
  deploy:
    jobs:
     - deploy:
     context: cf-worker